### ISSUE TITLE
Undefined behavior and some feedback

### ISSUE THREAD

**Issue by Jayshua** [Rocco-Jenson/box_raw_ptr#1]
Hello! I found some undefined behavior in this library. I also left some feedback at the bottom, hope you don't mind.

## Creating an unaligned reference without unsafe

The following code produces undefined behavior without an unsafe block:

```rust
let pointer = 20usize as *mut u64; // This pointer is not aligned
let boxed_pointer = box_raw_ptr::mut_raw_ptr::MutRawPtr::mut_new_ptr(pointer);
let undefined_behavior_ref: &u64 = thing.ref_mut().unwrap(); // Undefined behavior is here
```

Creating an unaligned reference is undefined behavior. [See the undefined behavior chapter in the Rust reference.](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) (The bullet point about producing invalid values.)

## Creating an &mut T from an &T

This also produces undefined behavior without an unsafe block:

```rust
let data: &usize = &23;
let thing = box_raw_ptr::mut_raw_ptr::MutRawPtr::mut_new_ptr(data as *const usize as *mut usize);
let mut_pointer = thing.mutref_mut().unwrap(); // Undefined behavior is here
*mut_pointer = 11; // Depending on the compiler flags this might produce a segfault
```

Creating an &mut T from an &T is always undefined behavior. [See the transmutes chapter in the nomicon.](https://doc.rust-lang.org/nomicon/transmutes.html)

----

This library is (currently) very unsafe. This should probably be documented on the crates.io page. Most of the functions in this library should probably be marked unsafe as well.

In general this library only seems to be focused on protecting against dereferencing a null pointer. However, there are many more rules that must be upheld when working with raw pointers in Rust than just that the pointer isn't null. Here are a few more:

- When dereferencing, the region of memory spanned by the type must lie entirely within a single allocation object. [See the safety section in the ptr primitive type docs.](https://doc.rust-lang.org/stable/std/ptr/index.html#safety)

- The pointer must be aligned. [See the ptr::as_ref() docs.](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.as_ref-1)

- Pointers must not be used to create aliasing references. [See the aliasing chapter in the nomicon.](https://doc.rust-lang.org/nomicon/aliasing.html)

There are more rules. [Behavior Considered Harmful](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html) and the [Nomicon](https://doc.rust-lang.org/stable/nomicon/) are good places to find more information.

### A few other notes

- It's not clear to me why you take the *mut T and [heap allocate it with Box::new()](https://docs.rs/box_raw_ptr/1.0.0/src/box_raw_ptr/lib.rs.html#509). This just creates a heap allocation containing the mutable pointer, which seems no different to me in terms of safety than just holding the *mut T pointer directly without putting it in a heap allocation.

- The docs on the `manual_drop` function appear to imply that producing a memory leak is unsafe. [Leaking memory is considered safe.](https://doc.rust-lang.org/book/ch15-06-reference-cycles.html)

- I'm pretty sure the `manual_drop` function is actually safe. You're just dropping a Box containing a *mut T. The only thing that should do is deallocate the heap allocation *containing* the *mut T pointer - it won't touch the memory that the *mut T was pointing at. Also, I didn't see an override for the default Drop impl (though I might have missed it), so the drop code will be run automatically when the MutRawPtr goes out of scope anyway, even without calling `manually_drop`.

I didn't look through all the code super carefully, so it's entirely possible that I'm completely off on some or all of this. If so, sorry about that!

**Comment by Rocco-Jenson** [comment]
Thank you for the help! I redesigned the library and changed the struct fields *mut T and *const T. Memory length and offset are also fields now. Alignment checking and null checking are included to eliminate undefined behaviour and bound checking is proper. If you would like to take a look again that would be appreciated. Thanks so much, Rocco.

**Comment by Jayshua** [comment]
Based on commit 26d044532419a187a1ca1d1ee8653e12162d09db

(Don't consider these comments to be exhaustive. They're just what I noticed in 20 minutes or so.)

Writing past the end of a stack-allocated array

```rust
let mut pointer: [u8; 3] = [0, 1, 2];
let mut mut_raw_ptr = box_raw_ptr::mut_raw_ptr::MutRawPtr::new(pointer.as_mut_ptr(), 4, 4);
mut_raw_ptr.write_ptr(1);
```


Dereferencing a null pointer

```rust
let mut thing = box_raw_ptr::mut_raw_ptr::MutRawPtr::nullptr();
thing.write_ptr(1);
```


Mutation of a non-mut value

```rust
let data: [u8; 3] = [0, 1, 2];
let thing = box_raw_ptr::const_raw_ptr::ConstRawPtr::new(data.as_ptr(), 3, 1);
let mut mutable_pointer = thing.as_mut();
mutable_pointer.write_ptr(1);
```


Reading uninitalized memory

```rust
#[derive(Copy, Clone, Debug)]
struct MyStruct {
	field_a: u8,
	field_b: u32,
}

let mut pointer = box_raw_ptr::mut_raw_ptr::MutRawPtr::<MyStruct>::c_malloc(1).unwrap();
let wrapper = box_raw_ptr::mut_raw_ptr::MutRawPtr::new(pointer, 1, 1);
let read_value = wrapper.ref_const().unwrap();
println!("{:?}", read_value);
```



Constructing a zero-sized allocation through std::alloc::alloc. [std::alloc::alloc is unsafe to call with an allocation size of 0](https://doc.rust-lang.org/stable/alloc/alloc/fn.alloc.html#safety)

```rust
let zero_sized_allocation = box_raw_ptr::mut_raw_ptr::MutRawPtr::<()>::c_malloc(5);
```

The first three examples also trigger the undefined behavior of calling `std::alloc::dealloc` with a pointer that wasn't allocated with `std::alloc::alloc`. (And the drop code additionally triggers a *third* undefined behavior of calling `std::alloc::dealloc` with a layout that might not be identical to the layout `std::alloc::alloc` was called with.)


I really recommend reading the Nomicon. It discusses most of these issues.



Here are some comments I added when reading through the code.



```diff
diff --git a/src/lib.rs b/src/lib.rs
index c403830..14d560c 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -222,7 +222,10 @@ pub mod const_raw_ptr {
         #[inline]
         pub fn new(ptr: *const T, memory_length: usize, offset: usize) -> Self {
             assert!((ptr as usize) % std::mem::align_of::<T>() == 0, "box_raw_ptr Err: Memory Not Aligned");
+
+            // Why can't offset be 0?
             assert!(offset <= memory_length && offset > 0, "box_raw_ptr Err: Offset Is Not Within Bounds");
+
             Self { ptr, memory_length, offset, }
         }
 
@@ -589,6 +592,11 @@ pub mod mut_raw_ptr {
         ///
         /// This function is unsafe because it performs a raw allocation and returns a raw pointer. The caller is responsible for ensuring that the memory is properly initialized and freed.
         ///
+        /// Allocating memory is not, by itself, inherently unsafe. Creating a raw pointer is not unsafe.
+        /// The actual reason this function is unsafe is because it calls std::alloc::alloc which exhibits undefined behavior when the length of memory passed to it is 0.
+        /// You do check if the requested length is 0, which *would* make it safe. But it's still possible to trigger a 0-sized allocation
+        /// if std::mem::size_of::<T>() == 0. For example: `let foo: MutRawPtr<()> = MutRawPtr::c_malloc(5);`
+        ///
+        /// By the way, there's no guarantee that std::alloc::alloc will call the libc allocator. It's both target-dependent and can be overridden by the user.
         /// # Example
         ///
         /// ```rust
@@ -604,6 +612,13 @@ pub mod mut_raw_ptr {
             let align: usize = std::mem::align_of::<T>();
             let layout: std::alloc::Layout = std::alloc::Layout::from_size_align(size, align).expect("Invalid alignment or size parameters.");
 
+            // It's customary to include a justification for each unsafe block as to why it is safe. For example:
+
+            /*
+            safety:
+            - std::alloc::alloc() is unsafe to call with a 0-sized allocation.
+            - Allocation was checked for non-zero above.
+            */
             unsafe {
                 let alloc: *mut T = std::alloc::alloc(layout) as *mut T;
                 return Some(alloc);
@@ -627,7 +642,11 @@ pub mod mut_raw_ptr {
         /// ```
         #[inline]
         pub fn new(ptr: *mut T, memory_length: usize, offset: usize) -> Self {
+            // Maybe use ptr.is_aligned()?
             assert!((ptr as usize) % std::mem::align_of::<T>() == 0, "box_raw_ptr Err: Memory Not Aligned");
+
+            // You may want to consider raw slice pointers which come bundled with a length
+            // *mut [T]
             assert!(offset <= memory_length && offset > 0, "box_raw_ptr Err: Offset Is Not Within Bounds");
             Self { ptr, memory_length, offset, }
         }
@@ -661,7 +680,7 @@ pub mod mut_raw_ptr {
         /// }
         /// ```
         #[inline]
-        pub unsafe fn manual_drop(self) -> () {
+        pub unsafe fn manual_drop(self) -> () { // No need for the "-> ()", that's the default if there's no return type.
             drop(self);
         }
 
@@ -775,7 +794,7 @@ pub mod mut_raw_ptr {
             if self.check_ptr() {
                 unsafe {
                     let ptr: T = *self.ptr;
-                    drop(self);
+                    drop(self); // Self will drop automatically when it goes out of scope at the end of this function
                     Some(ptr)
                 }
             } else {
@@ -787,6 +806,8 @@ pub mod mut_raw_ptr {
         /// 
         /// This method is useful for invalidating a mutable pointer and ensuring that it no longer points to any memory.
         /// 
+        /// It's not clear to me what you mean by "invalidating" a mutable pointer in this context.
+        /// 
         /// # Examples
         /// 
         /// ```rust
@@ -812,6 +833,26 @@ pub mod mut_raw_ptr {
         /// ```
         #[inline]
         pub fn memory_address(&self) -> String {
+            /*
+            This is kind of a weird function.
+            I probably would have just returned "self.ptr as usize"
+            since there seems to be little reason to perform a heap allocation here.
+            */
+
             format!("{:x}", self.ptr as usize)
         }
 
@@ -840,6 +881,8 @@ pub mod mut_raw_ptr {
         /// let value = mut_ptr.unwrap().unwrap();
         /// ```
         pub fn unwrap(self) -> Option<T> {
+            // The de-facto universal convention in Rust is that functions named "unwrap"
+            // panic if they can't perform the unwrap.
             if self.check_ptr() {
                 Some( unsafe { *self.ptr } )
             } else {
@@ -962,6 +1005,7 @@ pub mod mut_raw_ptr {
         }
     }
 
+    // This implementation appears identical to what #[derive(Debug)] would generate automatically
     impl<T: Sized + Copy + Send + Sync> std::fmt::Debug for MutRawPtr<T> {
         fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
             f.debug_struct("MutRawPtr")
@@ -972,6 +1016,10 @@ pub mod mut_raw_ptr {
         }
     }
 
+    // Testing for equality is not necessarily enough to determine if two pointers are equal.
+    // While pointers are represented by integers at the hardware level, to the compiler & optimizer
+    // they are more than just an address. Lookup pointer provenience for more information.
+    // I recommend reading ralfj.de's series of blog posts called "What's in a Byte" https://www.ralfj.de/blog/2018/07/24/pointers-and-bytes.html
     impl<T: Sized + Copy + Send + Sync> PartialEq for MutRawPtr<T> {
         fn eq(&self, other: &Self) -> bool {
             self.ptr == other.ptr
@@ -987,9 +1035,28 @@ pub mod mut_raw_ptr {
             if self.check_ptr() {
                 unsafe {
                     let layout: std::alloc::Layout = std::alloc::Layout::new::<T>();
+                    /*
+                    There are two safety requirements that must be followed to call std::alloc::dealloc.
+                    You can find them in the documentation for std::alloc::dealloc.
+                    This code violates both of them.
+
+                    1. the pointer given to dealloc must have been allocated with alloc.
+                       This crate makes it trivial to create a MutRawPtr containing an arbitrary pointer that may not have been allocated with alloc.
+                       This causes undefined behavior. On my machine, with the default global allocator on the x86_64-linux-gnu target
+                       it triggers a munmap_chunk exception. But that's not guaranteed. It could just as easily have failed silently or spawned a velociraptor.
+
+                    2. the layout given to dealloc must be identical to the layout given to alloc.
+                       There's no guarantee in this code that that will be the case. Maybe the the layout originally
+                       given to alloc allocated an entire array of these, in which case the size will be wrong.
+                   */
+
                     std::alloc::dealloc(self.ptr as *mut u8, layout);
                 }
             }
+
+            // No need for these steps. The memory storing self will be
+            // inaccessible after drop is run, so there won't be any way
+            // read these values regardless of whether they are overwritten here or not.
             self.memory_length = 0;
             self.offset = 0;
             self.ptr = std::ptr::null_mut();
@@ -997,6 +1064,9 @@ pub mod mut_raw_ptr {
     }
 }
 
+// You might want to take a look at Miri, which will run your rust code inside
+// a VM that can detect lots of undefined behavior and warn you about it.
+
 #[cfg(test)]
 mod box_raw_ptr_tests {
      use super::{const_raw_ptr::ConstRawPtr, mut_raw_ptr::MutRawPtr};

```

**Comment by Jayshua** [comment]
@Rocco-Jenson I stumbled across this library on crates.io again and noticed that there's still a lot of undefined behavior exposed in its safe API. (See my last comment on Jun 27th.) If you're fine with that then ok, but I really think it shouldn't claim that it is "providing safe abstractions" in the readme when it is not doing that.

Anyway, I've said my peace - I'll leave you alone now unless you'd like to correspond about it more. (Which I'm happy to do if you're interested!)

**Comment by Rocco-Jenson** [comment]
HI Jayshua,

Thank you for your feedback on my library! Things have been busy, but I am
coming around to fixing all these issues. If you happen to stumble across
any bugs later down the road please let me know. Thank you for all your
help, I really appreciate it.

Regards,
Rocco Jenson
